### ISSUE TITLE
Breaks Avalonia Rider Preview

### ISSUE THREAD

**Issue by seikosantana** [irihitech/Semi.Avalonia#252] opened 2023-09-04 07:12 UTC
Hi, I'm just getting started with Avalonia, and I want to try out this theme. I followed the instructions in newly created project form template and after applying the theme, the preview freezes. I tried using another theme and the issue doesn't happen. However, theme is applied during runtime, but seems to break design time.

Do i miss anything beside installing the Semi.Avalonia package and replacing fluent theme in Application.Styles?

Thanks in advance

**Comment by rabbitism** [comment] 2023-09-04 13:36
From Visual Studio building result I can see there is an error when using Semi.Avalonia. 
There must be somewhere I had static resource used but not defined in advance. I need to take a deep look at it, it's really hard to find the root cause...

![image](https://github.com/irihitech/Semi.Avalonia/assets/14807942/7d0ffb0e-8824-4ad0-85bc-00c07b4b83b5)

**Comment by rabbitism** [comment] 2023-09-04 16:13
System.Xaml.XamlException: 'Internal compiler error while transforming node XamlX.Ast.XamlAstNamePropertyReference:
XamlX.XamlTypeSystemException: Unable to resolve type Avalonia.Data.RelativeSource
   at XamlX.TypeSystem.XamlTypeSystemExtensions.GetType(IXamlTypeSystem sys, String type) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/TypeSystem/TypeSystem.cs:line 312
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.AvaloniaXamlIlWellKnownTypes..ctor(TransformerConfiguration cfg) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs:line 195
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.AvaloniaXamlIlWellKnownTypesExtensions.GetAvaloniaTypes(AstTransformationContext ctx) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlWellKnownTypes.cs:line 276
   at Avalonia.Markup.Xaml.XamlIl.CompilerExtensions.Transformers.AvaloniaXamlIlResolveClassesPropertiesTransformer.Transform(AstTransformationContext context, IXamlAstNode node) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/CompilerExtensions/Transformers/AvaloniaXamlIlClassesPropertyResolver.cs:line 18
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node) in /_/src/Markup/Avalonia.Markup.Xaml.Loader/xamlil.github/src/XamlX/Transform/AstTransformationContext.cs:line 62 Line 1, position 2.' Line number '1' and line position '2'.

**Comment by lukaspirkl** [comment] 2023-09-05 10:18
I have the same problem with the Previewer in the Visual Studio.

When I have the Fluent theme and the Semi theme at the same time, it works correctly. So maybe some required resource is not registered by the Semi.

```
<Application.Styles>
  <FluentTheme />
  <StyleInclude Source="avares://Semi.Avalonia/Themes/Index.axaml" />
  <StyleInclude Source="avares://Semi.Avalonia.ColorPicker/Index.axaml" />
  <StyleInclude Source="avares://Semi.Avalonia.DataGrid/Index.axaml" />
  <StyleInclude Source="avares://Semi.Avalonia.TreeDataGrid/Index.axaml" />
</Application.Styles>
```
```
<PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.4" />
<PackageReference Include="Semi.Avalonia" Version="11.0.1" />
<PackageReference Include="Semi.Avalonia.DataGrid" Version="11.0.1" />
<PackageReference Include="Semi.Avalonia.TreeDataGrid" Version="11.0.1" /> 
<PackageReference Include="Semi.Avalonia.ColorPicker" Version="11.0.1" /> 
```

**Comment by seikosantana** [comment] 2023-12-20 10:26
Just revisited Semi.Avalonia again today. Would really love to use this theme as it looks very nice, but it's hard to work with if rider preview does not work..

**Comment by rabbitism** [comment] 2023-12-20 14:49
> Just revisited Semi.Avalonia again today. Would really love to use this theme as it looks very nice, but it's hard to work with if rider preview does not work..

Thanks, Maybe I should ask avalonia team for help.

**Comment by seikosantana** [comment] 2023-12-20 14:53
Thanks

I also cloned the repo and found that the preview works in the demo project, just not if theme is consumed using nuget packages.

Wish i could do something about this but i dont have enough knowledge or expertise in avalonia

**Comment by fredericoregateiro** [comment] 2024-01-05 11:28
Same problem using VS 2022.
Add a reference to `<PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.6" />` fix the preview.

**Comment by rabbitism** [comment] 2024-02-12 08:07
@fredericoregateiro @seikosantana @lukaspirkl rumors said this issue is fixed in Avalonia 11.0.9 from upstream, could you please help to confirm?

**Comment by seikosantana** [comment] 2024-02-13 06:29
I'll try again shortly

**Comment by seikosantana** [comment] 2024-02-13 06:36
Confirmed that preview in rider now works without `Avalonia.Themes.Fluent`, haven't tried in Visual Studio.

Thanks a lot, I am now excited to switch to this theme.

**Closed** 2024-03-15 03:31 UTC
Labels: help wanted
